=== AshWije/Web-Programming/Stock-Data-Webpage/stockXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="allStocks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="stock" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="tickerSymbol">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z][A-Z][A-Z]" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="releaseDate" type="xs:date" />

              <xs:element name="price">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:decimal">
                      <xs:attribute name="currencyType" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <xs:element name="company" type="organization" />

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="organization">
    <xs:sequence>

      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Za-z0-9]*( [A-Z][A-Za-z0-9]*)*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="totalEmployees">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minExclusive value="0" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="country">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AshWije/Web-Programming/Stock-Data-Webpage/stockXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<allStocks xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="stockXMLSchema.xsd">

  <stock>
    <tickerSymbol>AFB</tickerSymbol>
    <releaseDate>1966-12-18</releaseDate>
    <price currencyType="NGN">45.78</price>
    <company>
      <name>Company N4</name>
      <totalEmployees>15</totalEmployees>
      <country>BT</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>FGU</tickerSymbol>
    <releaseDate>1967-04-06</releaseDate>
    <price currencyType="MRO">35.88</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>HXC</tickerSymbol>
    <releaseDate>1882-06-30</releaseDate>
    <price currencyType="NGN">45.80</price>
    <company>
      <name>Company N4</name>
      <totalEmployees>15</totalEmployees>
      <country>BT</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>XIW</tickerSymbol>
    <releaseDate>1843-09-09</releaseDate>
    <price currencyType="JPY">54.99</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>CCI</tickerSymbol>
    <releaseDate>1986-08-11</releaseDate>
    <price currencyType="CUP">88.38</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>OAM</tickerSymbol>
    <releaseDate>1991-04-12</releaseDate>
    <price currencyType="CUP">48.52</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>THF</tickerSymbol>
    <releaseDate>2015-06-05</releaseDate>
    <price currencyType="ZWL">4.03</price>
    <company>
      <name>Company N5</name>
      <totalEmployees>127</totalEmployees>
      <country>AO</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>XOA</tickerSymbol>
    <releaseDate>1905-02-21</releaseDate>
    <price currencyType="NGN">42.40</price>
    <company>
      <name>Company N4</name>
      <totalEmployees>15</totalEmployees>
      <country>BT</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>IDH</tickerSymbol>
    <releaseDate>1965-04-04</releaseDate>
    <price currencyType="JPY">11.69</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>DZT</tickerSymbol>
    <releaseDate>1893-04-28</releaseDate>
    <price currencyType="ZWL">44.40</price>
    <company>
      <name>Company N5</name>
      <totalEmployees>127</totalEmployees>
      <country>AO</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>YKT</tickerSymbol>
    <releaseDate>1961-08-16</releaseDate>
    <price currencyType="JPY">66.73</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>UOZ</tickerSymbol>
    <releaseDate>1980-12-04</releaseDate>
    <price currencyType="UZS">95.43</price>
    <company>
      <name>Company N8</name>
      <totalEmployees>127</totalEmployees>
      <country>AN</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>DPS</tickerSymbol>
    <releaseDate>1918-08-06</releaseDate>
    <price currencyType="UZS">33.70</price>
    <company>
      <name>Company N8</name>
      <totalEmployees>127</totalEmployees>
      <country>AN</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>KNO</tickerSymbol>
    <releaseDate>1812-02-17</releaseDate>
    <price currencyType="AED">4.01</price>
    <company>
      <name>Company N1</name>
      <totalEmployees>32</totalEmployees>
      <country>PH</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>XBE</tickerSymbol>
    <releaseDate>1974-11-05</releaseDate>
    <price currencyType="BGN">10.13</price>
    <company>
      <name>Company N6</name>
      <totalEmployees>51</totalEmployees>
      <country>SX</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>ZFF</tickerSymbol>
    <releaseDate>1890-06-05</releaseDate>
    <price currencyType="NZD">35.30</price>
    <company>
      <name>Company N10</name>
      <totalEmployees>143</totalEmployees>
      <country>BA</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>DQZ</tickerSymbol>
    <releaseDate>1972-07-29</releaseDate>
    <price currencyType="ZWL">25.06</price>
    <company>
      <name>Company N5</name>
      <totalEmployees>127</totalEmployees>
      <country>AO</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>RBJ</tickerSymbol>
    <releaseDate>1890-05-17</releaseDate>
    <price currencyType="CUP">71.95</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>QCE</tickerSymbol>
    <releaseDate>1928-01-29</releaseDate>
    <price currencyType="UZS">42.37</price>
    <company>
      <name>Company N8</name>
      <totalEmployees>127</totalEmployees>
      <country>AN</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>DGZ</tickerSymbol>
    <releaseDate>2010-04-25</releaseDate>
    <price currencyType="CUP">78.20</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>MET</tickerSymbol>
    <releaseDate>1839-09-28</releaseDate>
    <price currencyType="UZS">47.32</price>
    <company>
      <name>Company N8</name>
      <totalEmployees>127</totalEmployees>
      <country>AN</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>LYN</tickerSymbol>
    <releaseDate>1937-02-11</releaseDate>
    <price currencyType="CUP">13.30</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>EQJ</tickerSymbol>
    <releaseDate>1945-02-07</releaseDate>
    <price currencyType="JPY">49.65</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>DUL</tickerSymbol>
    <releaseDate>1879-07-23</releaseDate>
    <price currencyType="MRO">14.65</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>RRN</tickerSymbol>
    <releaseDate>1971-10-02</releaseDate>
    <price currencyType="BSD">58.36</price>
    <company>
      <name>Company N3</name>
      <totalEmployees>167</totalEmployees>
      <country>PH</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>WPA</tickerSymbol>
    <releaseDate>1983-07-05</releaseDate>
    <price currencyType="MRO">45.85</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>HYB</tickerSymbol>
    <releaseDate>1843-10-26</releaseDate>
    <price currencyType="MRO">13.28</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>YNY</tickerSymbol>
    <releaseDate>1982-01-12</releaseDate>
    <price currencyType="JPY">75.56</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>NSM</tickerSymbol>
    <releaseDate>1827-01-22</releaseDate>
    <price currencyType="MRO">1.74</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>ULM</tickerSymbol>
    <releaseDate>1815-06-16</releaseDate>
    <price currencyType="BGN">81.40</price>
    <company>
      <name>Company N6</name>
      <totalEmployees>51</totalEmployees>
      <country>SX</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>SPA</tickerSymbol>
    <releaseDate>1806-07-18</releaseDate>
    <price currencyType="JPY">32.26</price>
    <company>
      <name>Company N7</name>
      <totalEmployees>17</totalEmployees>
      <country>CK</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>NLJ</tickerSymbol>
    <releaseDate>1992-03-12</releaseDate>
    <price currencyType="MRO">9.27</price>
    <company>
      <name>Company N9</name>
      <totalEmployees>80</totalEmployees>
      <country>BQ</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>BRH</tickerSymbol>
    <releaseDate>1855-05-20</releaseDate>
    <price currencyType="ZWL">28.23</price>
    <company>
      <name>Company N5</name>
      <totalEmployees>127</totalEmployees>
      <country>AO</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>VQB</tickerSymbol>
    <releaseDate>1947-02-17</releaseDate>
    <price currencyType="CUP">87.96</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>URQ</tickerSymbol>
    <releaseDate>1871-04-07</releaseDate>
    <price currencyType="CUP">80.65</price>
    <company>
      <name>Company N2</name>
      <totalEmployees>149</totalEmployees>
      <country>PM</country>
    </company>
  </stock>

  <stock>
    <tickerSymbol>XFW</tickerSymbol>
    <releaseDate>1846-09-21</releaseDate>
    <price currencyType="UZS">78.14</price>
    <company>
      <name>Company N8</name>
      <totalEmployees>127</totalEmployees>
